let $RTP=split(&runtimepath, ',')[0]
let $VIMRC="$HOME/.vim/vimrc"

function InsertBreak()
  echo "fnt called"
  " compute line number of Breakpoints start
  " let temp = []
  " g/^test/call add(temp, line('.'))
  " append to filename
  " let lineNumber = line('.')
  " complete text to insert
  " echo expand('%:t')
  " b main.rs:10
  " commands
  " display config
  " print args
  " end
  " Insert before ?

endfunction
set nocompatible
filetype off
let mapleader=","
nnoremap ; :

call plug#begin()

Plug 'tpope/vim-commentary'
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-dispatch'

Plug 'jiangmiao/auto-pairs'

Plug 'preservim/tagbar'

Plug 'vimwiki/vimwiki'

Plug 'vim-airline/vim-airline'

Plug 'vyperlang/vim-vyper'

Plug 'nvie/vim-flake8'

Plug 'cespare/vim-toml'
Plug 'rust-lang/rust.vim'

call plug#end()

set autoread


syntax on                         " Turn on syntax highlighting
filetype on
filetype plugin indent on         " Add filetype, plugin, and indent support

set nospell
highlight SpellBad ctermbg=3

autocmd FileType gitcommit setlocal spell
autocmd BufNewFile,BufRead *.rs set filetype=rust
autocmd BufRead,BufNewFile *.py set filetype=python

set cursorline                  " underline where the cursor is
set showbreak=↪\ 
set listchars=tab:→\ ,eol:↲,nbsp:␣,trail:•,extends:⟩,precedes:⟨
set nolist
set backspace=indent,eol,start    " Backspace everything in insert mode
set formatoptions=tcroql          " Auto-wrap comments
set expandtab                     " Prefer spaces over tabs in general
set hidden                        " Prefer hiding over unloading buffers
set path=.,**                     " Relative to current file and everything under :pwd

set wildmode=longest,full         
set wildmenu                      " Display matches in command-line mode
set wildignore=**/node_modules/**,**/dist/**,*.pyc
set noswapfile                    " Disables swapfiles

set incsearch
set ignorecase smartcase



" Bindings for more efficient path-based file navigation
nnoremap <C-f> :find 
" nnoremap <leader>v :vert sfind 
" nnoremap ,F :find <C-R>=fnameescape(expand('%:p:h')).'/**/*'<CR>
" nnoremap ,V :vert sfind <C-R>=fnameescape(expand('%:p:h')).'/**/*'<CR>

" Useful for accessing commonly-used files
nnoremap <leader>rc :e $HOME/.bashrc<CR>
nnoremap <leader>r :e $RTP<CR>
nnoremap <leader>v :e $VIMRC<CR>
nnoremap <leader>f :e <C-R>='$RTP/after/ftplugin/'.&filetype.'.vim'<CR><CR>

" a or i onenter to enter comamnds
" <C-d> twice to exit
" nnoremap <leader>t :set nospell \| split \| term<CR>
nnoremap <Leader>s :%s/\<<C-r><C-w>\>/
nnoremap <leader>t :set nospell \| term<CR>

" Argslist navigation
nnoremap [a :previous<CR>
nnoremap ]a :next<CR>

" set tags=./tags;,tags;            " Find tags relative to current file and directory
" set wildcharm=<C-z>               " Macro-compatible command-line wildchar
" set t_BE=                         " Disable bracketed paste mode

"
" Copy current visual to system clipboard
map <leader>c "+y

" Kill bad habits
" inoremap <esc> <nop>
nnoremap <Up> <NOP>
nnoremap <Down> <NOP>
nnoremap <Left> <NOP>
nnoremap <Right> <NOP>
inoremap <Up> <NOP>
inoremap <Down> <NOP>
inoremap <Left> <NOP>
inoremap <Right> <NOP>
" inoremap jj <ESC>

" C-p completion
" set completeopt+=menuone,noselect,noinsert " don't insert text automatically
set pumheight=10 " keep the autocomplete suggestion menu small
set shortmess+=c " don't give ins-completion-menu messages



let g:vimwiki_list = [{'path': '~/vimwiki/',
			\ 'auto_diary_index':1,
      \ 'template_path': '~/vimwiki/templates/',
      \ 'template_default': 'default_hemant',
			\ 'auto_tags':1,
			\ 'ext': '.wiki'}]
" let g:vimwiki_global_ext = 0

nmap <F8> :TagbarToggle<CR><C-w><C-w>



" to able able to call nvim from command line with commands
command! Enter :normal<CR>

" to be installed from https://github.com/powerline/fonts
let g:airline_powerline_fonts = 1

let g:airline#extensions#tabline#enabled = 0
let g:airline#extensions#tabline#left_sep = ''
let g:airline#extensions#tabline#left_alt_sep = ''
let g:airline#extensions#tabline#right_sep = ''
let g:airline#extensions#tabline#right_alt_sep = ''


let g:airline_section_y=''
let g:airline_section_warning=''
let g:airline_section_error=''
let g:airline_section_z='%#__accent_bold#%p%% %#__accent_bold#%l%#__restore__#%#__accent_bold#/%L%'


let g:airline#extensions#fugitiveline#enabled = 1
let g:airline#extensions#branch#enabled = 1
let g:airline#extensions#branch#empty_message = ''
let g:airline#extensions#branch#vcs_priority = ["git"]

" ting and entering into insert within quote completion
" J as in Jump
nnoremap J la

augroup VCenterCursor
	au!
	au BufEnter,WinEnter,WinNew,VimResized *,*.*
				\ let &scrolloff=winheight(win_getid())/2
augroup END



" netrw
let g:netrw_banner = 0
let g:netrw_liststyle = 3
" let g:netrw_browse_split = 4
let g:netrw_altv = 1
let g:netrw_winsize = 25
let g:netrw_fastbrowse = 0


" dangerous
"set autochdir





" au BufWinLeave * mkview
" au BufWinEnter * silent loadview

" augroup ManageLastEditMark
" 	autocmd!
" 	if len(argv())>0
" 		silent echom "vim launched withs args"
" 		normal '.
" 	endif
" augroup END

" https://vi.stackexchange.com/questions/4120/how-to-enable-disable-an-augroup-on-the-fly
" https://vi.stackexchange.com/questions/2545/how-can-i-run-an-autocmd-when-starting-vim-with-no-file-a-non-existing-file-or
" au VimEnter * call HandleVimEnterGracefully()
" let g:ycm_auto_trigger = 0                       " Enable completion menu
" let g:ycm_min_num_of_chars_for_completion = 3
" let g:ycm_max_num_candidates = 20                " Max number of completion suggestions 
" let g:ycm_filetype_blacklist = {
" 			\ 'tagbar': 1,
" 			\ 'markdown': 1,
" 			\ 'netrw': 1,
" 			\ 'text': 1,
" 			\ 'vimwiki': 1,
" 			\ 'rust': 1,
" 			\}
" let g:ycm_filetype_whitelist = {
" 			\}

" let g:ycm_key_list_stop_completion = ['<C-y>']
" let g:ycm_key_invoke_completion = '<C-p>'


" let g:ycm_add_preview_to_completeopt = 0
" let g:ycm_autoclose_preview_window_after_insertion = 1
" let g:ycm_autoclose_preview_window_after_completion = 1

" let g:ycm_semantic_triggers =  {
" 			\   'rust': ['.', '::'],
" 			\}

" let g:ycm_error_symbol = 'xx'
" let g:ycm_open_loclist_on_ycm_diags = 1
" let g:ycm_always_populate_location_list = 1
" " Close preview window after completing the insertion

" let g:ycm_confirm_extra_conf = 0                 " Don't confirm python conf
" let g:ycm_always_populate_location_list = 1      " Always populae diagnostics list
" let g:ycm_enable_diagnostic_signs = 1            " Enable line highligting diagnostics
" let g:ycm_open_loclist_on_ycm_diags = 1          " Open location list to view diagnostics

" let g:ycm_auto_hover=''
" let g:ycm_max_num_identifier_candidates = 10     " Max number of identifier-based suggestions
" let g:ycm_show_diagnostic_ui = 1                 " Show diagnostic display features
" let g:ycm_enable_diagnostic_signs = 1            " Display icons in Vim's gutter, error, warnings
" let g:ycm_enable_diagnostic_highlighting = 1     " Highlight regions of diagnostic text
" let g:ycm_echo_current_diagnostic = 1            " Echo line's diagnostic that cursor is on
" let g:ycm_key_list_select_completion = ['<CTRL-P>']

